### PR TITLE
build riscv buildroot rootfs

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nathanchance** [comment]
Needs the config and rebuild.sh update as well for future updates/changes. Might not be a terrible time to add support to boot-qemu.sh as well.

**Comment by nathanchance** [comment]
Otherwise I have a working command line that I can pull tonight if we just want to ship the rootfs now.

**Comment by nathanchance** [comment]
https://github.com/nathanchance/boot-utils/commits/riscv

**Comment by nickdesaulniers** [comment]
@nathanchance yeah your patch looks much more filled out and ready to go. Let's take that instead.

**Comment by nickdesaulniers** [comment]
Not sure how I have the root image, but not the config. Not sure how I built it...

**Pull request closed without merging**
