### PR TITLE
add x86 images

### PR DESCRIPTION
**Pull request by nickdesaulniers**
The config is copied from buildroot/x86_64.config modulo CONFIG_64B.

Boot tested with a 32b x86 Clang built kernel in qemu.

Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
should help https://github.com/ClangBuiltLinux/continuous-integration/pull/182

note, I don't see `/proc/version` in interactive mode, but that's just another bug to chase.

**Comment by nathanchance** [comment]
> note, I don't see `/proc/version` in interactive mode, but that's just another bug to chase.

`mount -t proc proc /proc`

When we jump straight into a shell, init does not run to automatically mount all of those systems.

**Comment by nickdesaulniers** [comment]
oh, I didn't realize that init was mounting proc. makes sense

**Comment by tpimh** [comment]
That's practically identical to my [i386 branch](https://github.com/ClangBuiltLinux/boot-utils/tree/i386).

**Comment by nickdesaulniers** [comment]
ah, sorry I didn't see it @tpimh , send those PRs ASAP!

**Pull request merged**
