### PR TITLE
boot-qemu.sh: Use different CPU for arm64 with new QEMU + old kernel

### PR DESCRIPTION
**Pull request by nathanchance**
After FEAT_LPA was implemented in QEMU's TCG, kernels older than 4.19,
namely 4.9 and 4.14, fail to boot. We already have a workaround for
FEAT_LPA2 not working with kernels older than 5.12, which is known.
Reporting this to QEMU upstream resulted in the recommendation to use
one of the ARMv8.0 CPUs for these older kernels. Use 'cortex-a72' for
booting anything older than 4.19 with QEMU 6.2.50 (master) and newer.

Link: https://gitlab.com/qemu-project/qemu/-/issues/964

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
From that thread, it sounds like there's perhaps a missing backport we should take into stable instead?
https://gitlab.com/qemu-project/qemu/-/issues/964#note_903279226

**Comment by nathanchance** [comment]
Maybe, I'll see.

**Comment by nathanchance** [comment]
I've updated the kernel check based https://gitlab.com/qemu-project/qemu/-/issues/964#note_903403849.

**Review by nickdesaulniers — APPROVED** [review]
thanks for running the bisection to identify the change, the asses the risks in backporting it. Looks like this is the way to go. :id: :fountain:

**Comment by nathanchance** [comment]
Thanks for double checking my analysis as always!

**Pull request merged**
